/**
 * Shared version-bridge core.
 *
 * Docusaurus expects versioned docs under `<pluginId>_versioned_docs/`,
 * versioned sidebars under `<pluginId>_versioned_sidebars/`, and a
 * `<pluginId>_versions.json` listing. Rather than maintain those by hand we
 * keep the canonical source in the repo (versions/<id>/, protocol/<id>/) and
 * regenerate the Docusaurus build output synchronously at config-eval time.
 *
 * This module holds the plugin-agnostic machinery; spec-version-bridge.ts and
 * protocol-version-bridge.ts are thin wrappers that supply the source dir,
 * plugin id, sidebar module, and the set of released version ids.
 */

import * as fs from 'fs';
import * as path from 'path';

export function copyDirSync(src: string, dest: string): void {
  fs.mkdirSync(dest, {recursive: true});
  for (const entry of fs.readdirSync(src, {withFileTypes: true})) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function loadSidebar(sidebarModule: string): object {
  // Import the live sidebars file so versioned sidebars stay in sync.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = require(sidebarModule);
  return mod.default ?? mod;
}

/**
 * Walk a version's doc directory and return the set of doc ids that exist.
 * Doc id resolution follows Docusaurus convention: either the frontmatter
 * `id:` or the path-derived basename (folder/filename-without-ext for nested
 * files, filename-without-ext for top-level files).
 */
function listDocIds(rootDir: string): Set<string> {
  const ids = new Set<string>();
  if (!fs.existsSync(rootDir)) return ids;

  function walk(dir: string, prefix: string): void {
    for (const entry of fs.readdirSync(dir, {withFileTypes: true})) {
      const full = path.join(dir, entry.name);
      const next = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(full, next);
      } else if (entry.name.endsWith('.md') || entry.name.endsWith('.mdx')) {
        const content = fs.readFileSync(full, 'utf-8');
        const idMatch = content.match(/^---[\s\S]*?\nid:\s*(\S+)/);
        const baseName = entry.name.replace(/\.(md|mdx)$/, '');
        const explicitId = idMatch?.[1];
        const fullId = prefix
          ? explicitId
            ? `${prefix}/${explicitId}`
            : `${prefix}/${baseName}`
          : explicitId ?? baseName;
        ids.add(fullId);
      }
    }
  }
  walk(rootDir, '');
  return ids;
}

interface SidebarItem {
  type?: string;
  id?: string;
  items?: unknown[];
  link?: {type?: string; id?: string};
  [k: string]: unknown;
}

/**
 * Filter a single sidebar item, returning the item or null if it references a
 * doc id not present in `validIds`. Categories whose link or items all
 * evaporate are dropped. Non-doc items (external links, refs) are kept.
 */
function filterSidebarItem(
  item: unknown,
  validIds: Set<string>,
): unknown | null {
  if (item === null || item === undefined) return null;
  if (typeof item === 'string') {
    return validIds.has(item) ? item : null;
  }
  if (typeof item !== 'object') return item;

  const obj = item as SidebarItem;

  if (obj.type === 'doc') {
    return typeof obj.id === 'string' && validIds.has(obj.id) ? obj : null;
  }

  if (obj.type === 'category') {
    const filteredItems = Array.isArray(obj.items)
      ? (obj.items
          .map((sub) => filterSidebarItem(sub, validIds))
          .filter((sub) => sub !== null) as unknown[])
      : [];
    const linkValid =
      !obj.link ||
      obj.link.type !== 'doc' ||
      (typeof obj.link.id === 'string' && validIds.has(obj.link.id));

    if (!linkValid) return null;
    if (filteredItems.length === 0 && (!obj.link || obj.link.type !== 'doc')) {
      return null;
    }
    return {...obj, items: filteredItems};
  }

  // type === 'link' (external), 'ref', 'html', 'autogenerated' — pass through unchanged
  return obj;
}

/**
 * Filter the whole sidebars config (object whose values are sidebar arrays).
 */
function filterSidebar(sidebars: unknown, validIds: Set<string>): unknown {
  if (sidebars === null || typeof sidebars !== 'object') return sidebars;
  if (Array.isArray(sidebars)) {
    return sidebars
      .map((item) => filterSidebarItem(item, validIds))
      .filter((item) => item !== null);
  }
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(sidebars)) {
    out[key] = filterSidebar(value, validIds);
  }
  return out;
}

export interface BridgeOptions {
  /** The Docusaurus site directory (where the *_versioned_* output lives). */
  siteDir: string;
  /** Absolute path to the directory holding the version subdirectories. */
  sourceDir: string;
  /** Docusaurus content-docs plugin id, e.g. 'spec' or 'protocol'. */
  pluginId: string;
  /** Absolute path to the live sidebars module for this plugin. */
  sidebarModule: string;
  /** Released version ids to bridge, newest first. */
  versionIds: string[];
}

/**
 * Synchronously bridge `sourceDir/<id>/` → `<pluginId>_versioned_docs/`.
 * Returns the version ids that were actually written (source existed).
 * Call this at config-eval time, before Docusaurus initializes the plugin.
 */
export function bridgeVersions(opts: BridgeOptions): string[] {
  const {siteDir, sourceDir, pluginId, sidebarModule, versionIds} = opts;
  if (versionIds.length === 0) return [];

  const versionedDocsDir = path.join(siteDir, `${pluginId}_versioned_docs`);
  const versionedSidebarsDir = path.join(siteDir, `${pluginId}_versioned_sidebars`);
  fs.mkdirSync(versionedDocsDir, {recursive: true});
  fs.mkdirSync(versionedSidebarsDir, {recursive: true});

  const written: string[] = [];

  for (const id of versionIds) {
    const src = path.join(sourceDir, id);
    const dest = path.join(versionedDocsDir, `version-${id}`);

    if (!fs.existsSync(src)) {
      console.warn(`[${pluginId}-version-bridge] ${src} not found, skipping`);
      continue;
    }

    // Always refresh to pick up any source changes.
    if (fs.existsSync(dest)) {
      fs.rmSync(dest, {recursive: true, force: true});
    }
    copyDirSync(src, dest);

    // Generate the versioned sidebar from the live sidebar module, filtered to
    // only reference docs that exist in this version.
    const validIds = listDocIds(dest);
    const filtered = filterSidebar(loadSidebar(sidebarModule), validIds);
    fs.writeFileSync(
      path.join(versionedSidebarsDir, `version-${id}-sidebars.json`),
      JSON.stringify(filtered, null, 2) + '\n',
    );
    written.push(id);
  }

  fs.writeFileSync(
    path.join(siteDir, `${pluginId}_versions.json`),
    JSON.stringify(written) + '\n',
  );

  return written;
}
